### ISSUE TITLE
Modified files immediately after repo clone

### ISSUE THREAD

**Issue by jlmuir** [mxcube/mxcubeqt#124]
If I do a fresh clone, change my working directory to the newly cloned repo, and then run the Git `status` command, it says I have modified files already:

```
$ cd /tmp
$ git clone https://github.com/mxcube/mxcube.git
Cloning into 'mxcube'...
remote: Counting objects: 14422, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 14422 (delta 235), reused 216 (delta 216), pack-reused 14174
Receiving objects: 100% (14422/14422), 151.63 MiB | 71.14 MiB/s, done.
Resolving deltas: 100% (10200/10200), done.
Checking connectivity... done.
$ cd mxcube
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml
    modified:   ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
    modified:   ExampleFiles/HardwareObjects.xml/soleil_px2/frontendAtt.xml
    modified:   ExampleFiles/HardwareObjects.xml/soleil_px2/obxAtt.xml
    modified:   ExampleFiles/HardwareObjects.xml/soleil_px2/sampX.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

Running the Git `diff` command on the first two modified files shows various changes that I did not make:

```
$ git diff ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
diff --git a/ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml b/ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml
index 2c9a1d8..798364b 100644
--- a/ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml
+++ b/ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml
@@ -1,5 +1,5 @@
 <device class = "Ps_attenuatorPX1">
-  <username>Attenuators by Primary Slits</username>
+  <username>Attenuators by Primary slits</username>
   <tangoname>i10-c-c00/ex/fp_parser</tangoname>
   <channel type="tango" polling="1000" name="TrueTrans_FP">TrueTrans_FP</channel>
   <channel type="tango" polling="1000" name="State">State</channel>
diff --git a/ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml b/ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
index 385ad2f..6da4c5e 100644
--- a/ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
+++ b/ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
@@ -1,8 +1,8 @@
-<device class="TangoShutterPX1">
+<device class="InOut">
     <username>FastShutter</username>
     <tangoname>i11-ma-cx1/ex/md2</tangoname>
-    <command type="tango" tangoname="i11-ma-cx1/ex/md2" name="open">OpenFastShutter</command>
-    <command type="tango" tangoname="i11-ma-cx1/ex/md2" name="close">CloseFastShutter</command>
+    <command type="tango" tangoname="i11-ma-cx1/ex/md2" name="set_in">OpenFastShutter</command>
+    <command type="tango" tangoname="i11-ma-cx1/ex/md2" name="set_out">CloseFastShutter</command>
     <channel type="tango" tangoname="i11-ma-cx1/ex/md2" polling="1000" name="state">State</channel>
 </device>
```

I'm on OS X El Capitan.

**Comment by mguijarr** [comment]
Hi Lewis,

Thanks for pointing this.

Unfortunately it is not so easy to solve, see [this question](http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git)

I just added a `.gitattributes` file to MXCuBE repository, and normalized all line endings following
this [link](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings).

I think the problem is solved but I am not sure since I could not see it by myself as I am running ubuntu (other information in this long thread [here](http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone)).

Could you please give it another try and see if the issue is solved now ?

Thanks in advance !

**Comment by jlmuir** [comment]
Hello, Matias!

Thanks for taking a look at this.  I tried again after your change, but, unfortunately, the problem persists.

Perhaps line endings were part of the problem, but, continuing to look, and noticing that the diffs are not line-ending-only diffs, I think the issue is with a case-insensitive file system.  HFS+ on OS X El Capitan is case-_insensitive_, while ext4 (or presumably whatever) on Ubuntu is case-_sensitive_.  Based on [Sam Elliott's answer on Stack Overflow](http://stackoverflow.com/a/5022417), I used Git's `ls-tree` command and was able to see that all of the files initially listed as modified have an evil twin that has the same name, but at least one character's case has been inverted (only the output for the twins is shown):

```
$ git ls-tree -r HEAD ExampleFiles/HardwareObjects.xml/soleil_px1
100644 blob 2c9a1d815fc286ebb770bd4f3a75490213874d3f    ExampleFiles/HardwareObjects.xml/soleil_px1/PS_attenuator.xml
100644 blob 798364b994ddc5990d6274620b3a0384b0fe649f    ExampleFiles/HardwareObjects.xml/soleil_px1/Ps_attenuator.xml
$ git ls-tree -r HEAD ExampleFiles/HardwareObjects.xml/soleil_px2
100644 blob 385ad2f8b3404dc00de4d7909740679518ca4b62    ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutterAtt.xml
100644 blob 6da4c5e6d7c1fc609c2042f90ce3e0d01b02c318    ExampleFiles/HardwareObjects.xml/soleil_px2/fastshutteratt.xml
100644 blob 8fabe8fd9d3e59ffd7414cd5fa51c82e33d9b415    ExampleFiles/HardwareObjects.xml/soleil_px2/frontendAtt.xml
100644 blob 7e5271baf0d66cbe1367f10ffdb7f1f99e9199bb    ExampleFiles/HardwareObjects.xml/soleil_px2/frontendatt.xml
100644 blob 0d910825b8d0dca4e1f0e508e2b42d9701da1300    ExampleFiles/HardwareObjects.xml/soleil_px2/obxAtt.xml
100644 blob 8a3a8cf853abf27c8250beef167df32254c9c8eb    ExampleFiles/HardwareObjects.xml/soleil_px2/obxatt.xml
100644 blob 5b72fe04ffb79e0ac58e87f1c414171ea237b34c    ExampleFiles/HardwareObjects.xml/soleil_px2/sampX.xml
100644 blob 875f20fceed14740658ab1e5c2fda1325879162b    ExampleFiles/HardwareObjects.xml/soleil_px2/sampx.xml
```

It turns out this can also be seen by simply browsing the tree on GitHub.

So, I think if one of each of the twin files could be deleted, that would solve the problem?  I guess you'd have to figure out which one of each pair should be deleted, though.

**Comment by jlmuir** [comment]
@MartinSavko:

Hello, Martin!  It looks like you committed the example SOLEIL files on July 15, 2015 in commit 6e1c86f to `HardwareObjects.xml/PX1` and `HardwareObjects.xml/PX2`.  These were later moved by Ivars to `ExampleFiles/HardwareObjects.xml/soleil_px1` and `ExampleFiles/HardwareObjects.xml/soleil_px2`, respectively.  It seems that some of the example XML files got committed with a duplicate name where the case of at least one character has been inverted.  Unfortunately, this causes trouble on a case-insensitive file system like HFS+ on OS X.  One of each duplicate should be removed from the repository, but it's not obvious to me which one it should be.  The files are as follows.

In `ExampleFiles/HardwareObjects.xml/soleil_px1`:
- `PS_attenuator.xml` and `Ps_attenuator.xml`
  
  Should `PS_attenuator.xml` be removed?

In `ExampleFiles/HardwareObjects.xml/soleil_px2`:
- `fastshutterAtt.xml` and `fastshutteratt.xml`
  
  Should `fastshutteratt.xml` be removed?
- `frontendAtt.xml` and `frontendatt.xml`
  
  Should `frontendatt.xml` be removed?
- `obxAtt.xml` and `obxatt.xml`
  
  Should `obxatt.xml` be removed?
- `sampX.xml` and `sampx.xml`
  
  Should `sampX.xml` be removed?  That would leave `sampx.xml` which is consistent with the existing `sampy.xml`.

Could you please advise?  Thanks!

**Comment by jlmuir** [comment]
Works now.  Thanks, Martin!
